<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="TP_6.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

    <title></title>
</head>
<body>
    <h1 class="text-center p-4 text-xl font-bold text-purple-900">Productos</h1>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="grd_Products" runat="server"
                AutoGenerateColumns="False"
                AllowPaging="True"
                PageSize="15"
                OnPageIndexChanging="grd_Products_PageIndexChanging"
                CssClass="max-w-[600px] mx-auto border border-gray-300 shadow-lg rounded-lg overflow-hidden"
                PagerStyle-CssClass="w-full flex justify-center space-x-2 p-3 bg-purple-600 text-white"
                HeaderStyle-CssClass="bg-purple-700 text-white p-4 text-center uppercase text-sm"
                RowStyle-CssClass="bg-white text-gray-700 border-b border-gray-200"
                AlternatingRowStyle-CssClass="bg-gray-100 text-gray-700"
                SelectedRowStyle-CssClass="bg-purple-200 font-bold"
                SortedAscendingHeaderStyle-CssClass="bg-purple-400"
                SortedDescendingHeaderStyle-CssClass="bg-purple-600 w-full " 
                AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" 
                OnRowDeleting="Deleting" 
                OnRowEditing="Editing" 
                OnRowCancelingEdit="Cancel" 
                OnRowUpdating="Updating">

                <Columns>
                    <asp:TemplateField HeaderText="ID Producto">
                        <ItemTemplate>
                            <asp:Label ID="lblID" runat="server"
                                CssClass="block p-2 text-center font-semibold"
                                Text='<%# Eval("IdProducto") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:Label ID="lbl_eit_ID" runat="server"
                                CssClass="block p-2 text-center font-semibold"
                                Text='<%# Eval("IdProducto") %>'></asp:Label>
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Nombre">
                        <ItemTemplate>
                            <asp:Label ID="lblNombre" runat="server"
                                CssClass="block p-2 text-center"
                                Text='<%# Eval("NombreProducto") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:Textbox ID="txt_eit_Nombre" runat="server"
                                CssClass="block p-2 text-center"
                                Text='<%# Eval("NombreProducto") %>'></asp:Textbox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Cantidad por Unidad">
                        <ItemTemplate>
                            <asp:Label ID="lblCantidad" runat="server"
                                CssClass="block p-2 text-center"
                                Text='<%# Eval("CantidadPorUnidad") %>'></asp:Label>
                        </ItemTemplate>
                       <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Cantidad" runat="server"
                                CssClass="block p-2 text-center"
                                Text='<%# Eval("CantidadPorUnidad") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Precio Unitario">
                        <ItemTemplate>
                            <asp:Label ID="lblPrecio" runat="server"
                                CssClass="block p-2 text-center"
                                Text='<%# Eval("PrecioUnidad") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Precio" runat="server"
                                CssClass="block p-2 text-center"
                                Text='<%# Eval("PrecioUnidad") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>

        </div>
    </form>
</body>
</html>
